# Generated by Django 5.0.7 on 2024-07-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_country_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
