# Generated by Django 5.0.7 on 2024-08-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_chatroomlatam_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomOcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='chatroomsocio/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryOcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='subcategoriesocio/')),
                ('url', models.URLField()),
            ],
        ),
    ]
