# Generated by Django 5.0.7 on 2024-08-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_chatroom_url_alter_chatroomlatam_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryParaguay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='subcategoriesparaguay/')),
                ('url', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
