# Generated by Django 5.0.7 on 2024-08-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_iframetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IframeToken',
        ),
    ]
